version: "3.8"
services:

  postgres:
    image: postgres
    container_name: local_pgdb
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - api-db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: super@admin.com
      PGADMIN_DEFAULT_PASSWORD: superpassword
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
      - "8081:8081"
    depends_on:
      - redis

  bullboard:
    container_name: bullboard
    image: deadly0/bull-board
    restart: always
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      BULL_PREFIX: bull
      USER_LOGIN: "yemo"
      USER_PASSWORD: "password"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  api-db:
  pgadmin-data:
